// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovexmodtxagtxwabykfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92ZXhtb2R0eGFndHh3YWJ5a2ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDY4NjAsImV4cCI6MjA2NzcyMjg2MH0.yEv0iW7dFhO6wMlK7aXffY_Mfm4pw3C8FNPxqa9yx0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});